mysite/blog/urls.py
from django.conf.urls import url
from . import views
from .views import TagIndexView, PostDetail, PostSearch
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from .feeds import PostsFeed

sitemaps = {
    'posts' : PostSitemap
}

urlpatterns = [
    # Widoki posta
    #url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^tag/(?P<slug>[-\w]+)/$', TagIndexView.as_view(), name='tagged'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<slug>[-\w]+)/$',
        PostDetail.as_view(),
        name='post_detail'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps' : sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', PostsFeed(), name='post_feed'),
    url(r'^search/$', PostSearch.as_view(), name='post_search')
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^comments/', include('django_comments_xtd.urls')),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Roboczy'),
        ('published', 'Opublikowany'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = RichTextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    allow_comments = models.BooleanField(default=True)
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.strftime('%m'),
                              self.publish.strftime('%d'),
                              self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

mysite/blog/forms.py
from django import forms
from haystack.forms import SearchForm

class MySearchForm(SearchForm):
    pass

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from taggit.models import Tag
from django.views.generic import ListView, DetailView
from haystack.generic_views import SearchView
from haystack.query import SearchQuerySet
from .forms import MySearchForm

class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

# Create your views here.
class PostListView(TagMixin, ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    temlate_name = 'blog/post_list.html'
    model = Post

class PostDetail(DetailView):
    template_name = 'blog/post/detail.html'
    context_object_name = 'post'
    model = Post
    slug_field = 'slug'

class TagIndexView(TagMixin, ListView):
    template_name = 'blog/post_list.html'
    model = Post
    paginate_by = 3
    context_object_name = 'posts'

    def get_queryset(self):
        tag = self.kwargs.get('slug')
        return Post.published.filter(tags__slug=self.kwargs.get('slug'))

class PostSearch(SearchView):
    template_name = 'blog/post/search.html'
    queryset = SearchQuerySet()
    form_class = MySearchForm
    paginate_by = 3

mysite/blog/templates/blog/base.html
{% load staticfiles %}
{% load taggit_templatetags2_tags %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>    
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'assets/css/blog.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
        crossorigin="anonymous"/>
</head>

<body>
    <div class="blog-masthead">
        <div class="container">
            <nav class="nav">
                <a class="nav-link active" href="{% url 'blog:post_list' %}">Blog</a>
            </nav>
        </div>
    </div>
    <div class="blog-header">
        <div class="container">
            <h1 class="blog-title">The Bootstrap Blog</h1>
            <p class="lead blog-description">An example blog template built with Bootstrap.</p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-8 blog-main">
                {% block content %} {% endblock %}
            </div>
            <div class="col-sm-3 offset-sm-1 blog-sidebar">
                    <div class="sidebar-module">
                        <h4>Search</h4>
                        <form id="search" action="/blog/search/" method="get" class="searchbar" autocomplete="off" role="search">
                            <input name="q" type="text" placeholder="Search…" value="" tabindex="1" autocomplete="off" maxlength="240" class="f-input js-search-field">
                            <input type="submit" value="Szukaj">
                        </form>
                    </div>
                    <div class="sidebar-module sidebar-module-inset">
                            <h4>About</h4>
                            <p>To jest mój blog</p>
                            <p><a href="{% url 'blog:post_feed' %}">Subskrybuj kanał</a></p>
                    </div>
                    <div class="sidebar-module">
                        <h4>Tags</h4>
                        {% get_tagcloud as tags for 'blog' %}
                        {% for tag in tags %}
                            <a href="{% url 'blog:tagged' tag.slug %}" rel="tag" class="tag{{ tag.num_times }}">{{ tag }}</a>
                        {% endfor %}
                    </div>
            </div>
        </div>
    </div>
</body>

</html>

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load comments %}
{% load comments_xtd %}

{% block  title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="blog-post">
        <h2 class="blog-post-title">
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="blog-post-meta">
            Opublikowany {{ post.publish }} przez {{ post.author }}
        </p>
        Tagi:
        {% for tag in post.tags.all %}
        <span class="tag tag-pill tag-default">
            <a href="{% url 'blog:tagged' tag.slug %}" rel="tag">
                {{ tag.name }}
            </a>
        </span>
        {% endfor %}
        {% autoescape off %}
            {{ post.body|linebreaks }}
        {% endautoescape %}
    </div>
    {% get_comment_count for post as comment_count %}
    <div class="text-center" style="padding-top:20px">
      <a href="{% url 'blog:post_list' %}">Back to the post list</a>
      &nbsp;&sdot;&nbsp;
      {{ comment_count }} comments have been posted.
    </div>
    
    {% if post.allow_comments %}
    <div class="comment">
      <h4 class="text-center">Your comment</h4>
      <div class="well">
        {% render_comment_form for post %}
      </div>
    </div>
    {% endif %}
    
    {% if comment_count %}
    <hr/>
    <ul class="media-list">
      {% render_xtdcomment_tree for post %}
    </ul>
    {% endif %}
{% endblock content %}

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}Mój blog{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="blog-post">
            <h2 class="blog-post-title">
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="blog-post-meta">
                Opublikowany {{ post.publish }} przez {{ post.author }}
            </p>
            {% autoescape off %}
                {{ post.body|truncatewords:30|linebreaks }}
            {% endautoescape %}
        </div>
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load comments %}

{% block title %}Szukaj{% endblock %}

{% block content %}
        {% if query %}
        <h3>Results</h3>
            {% for result in object_list %}
            <div class="blog-post">
                <h2 class="blog-post-title">
                    <a href="{{ result.object.get_absolute_url }}">
                        {{ result.object.title }}
                    </a>
                </h2>
                <p class="blog-post-meta">
                    Opublikowany {{ result.object.publish }} przez {{ result.object.author }}
                </p>
                Tagi:
                {% for tag in result.object.tags.all %}
                <span class="tag tag-pill tag-default">
                    <a href="{% url 'blog:tagged' tag.slug %}" rel="tag">
                        {{ tag.name }}
                    </a>
                </span>
                {% endfor %}
                {% autoescape off %}
                    {{ result.object.body|truncatewords:30|linebreaks }}
                {% endautoescape %}
            </div>
            <p class="date">
                {% get_comment_count for result.object as comment_count %}
                {% if comment_count %}
                &sdot;&nbsp;{{ comment_count }} comments
                {% endif %}
              </p>
            {% empty %}
            <p>No results found.</p>
            {% endfor %}
            {% include "pagination.html" with page=page_obj %}
        {% else %}
        <form type="get" action=".">
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Search"></td>
              </tr>
            </table>
        </form>
        {% endif %}
        </form>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load comments %}

{% block title %}Mój blog{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="blog-post">
            <h2 class="blog-post-title">
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>
            <p class="blog-post-meta">
                Opublikowany {{ post.publish }} przez {{ post.author }}
            </p>
            Tagi:
            {% for tag in post.tags.all %}
            <span class="tag tag-pill tag-default">
                <a href="{% url 'blog:tagged' tag.slug %}" rel="tag">
                    {{ tag.name }}
                </a>
            </span>
            {% endfor %}
            {% autoescape off %}
                {{ post.body|truncatewords:30|linebreaks }}
            {% endautoescape %}
        </div>
        <p class="date">
            {% get_comment_count for post as comment_count %}
            {% if comment_count %}
            &sdot;&nbsp;{{ comment_count }} comments
            {% endif %}
          </p>
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

mysite/blog/templates/pagination.html
<ul class="pagination">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">
              &laquo;
          </span>
        </a>
      </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
      {% if page.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">
            {{i}}<span class="sr-only">(current)</span>
          </a>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">&raquo;</a></li>
    {% endif %}
</ul>